layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: annie-helms-516a27b9
  # mastodon: your_username
  # medium: your_username
  orcid: 0000-0001-9960-3351
  # stackoverflow: your_user_id
  researchgate: Annie_Helms
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
   - name: Research
     web_url: http://anniehelms.github.io/research
     image_url: https://cdn1.iconfinder.com/data/icons/journalist-4/64/recorder-voice-sound-audio-digital-512.png

   - name: Teaching
     web_url: http://anniehelms.github.io/teaching
     image_url: https://cdn2.iconfinder.com/data/icons/talking-speech-discussion-presentation/512/N_F009_09_TalkingArtboard_1_copy_4-512.png

   - name: CV
     web_url: "https://anniehelms.github.io/files/Helms_CV.pdf"
     image_url: https://cdn2.iconfinder.com/data/icons/business-and-finance-369/30/resume_business_cv_work_job_curriculum-_10-512.png

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 6
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name
